# Generated by Django 4.1.5 on 2023-01-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ethnicity',
            field=models.CharField(choices=[('White', 'White'), ('African American', 'African American'), ('Hispanic', 'Hispanic'), ('Native Hawaiian/Pacific Islander', 'Native Hawaiian/Pacific Islander'), ('Asian American', 'Asian American')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sex_at_birth',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unsure')], max_length=1, null=True),
        ),
    ]
