# Generated by Django 4.1.5 on 2023-02-01 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='symptoms',
            field=models.ManyToManyField(related_name='diagnoses', to='health.symptom'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='users',
            field=models.ManyToManyField(related_name='diagnoses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='users',
            field=models.ManyToManyField(related_name='symptoms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(related_name='trigger_foods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
